services:
    peterjmit_blog.controller.blog:
        class: Peterjmit\BlogBundle\Controller\BlogController
        arguments:
            - @peterjmit_blog.repository.blog
            - @templating

    peterjmit_blog.repository.blog:
        class: Peterjmit\BlogBundle\Repository\BlogRepository
        arguments:
            - @entity_manager


